Repository LibrePDF/OpenPDF, pull requests merged in 2019-08, with the labels that each got.

#220 Fix bug concerning stroke colors when simulating bold fonts.
  openpdf/src/main/java/com/lowagie/text/pdf/PdfGraphics2D.java
Labels: Needs work, bug, help wanted

#222 #216: Fix binary transparency bug
  openpdf/src/main/java/com/lowagie/text/Image.java
Labels: bug, need-info

#219 Remove warnings 5
  openpdf/src/main/java/com/lowagie/text/pdf/AcroFields.java
  openpdf/src/main/java/com/lowagie/text/pdf/BarcodeDatamatrix.java
  openpdf/src/main/java/com/lowagie/text/pdf/BarcodePDF417.java
  openpdf/src/main/java/com/lowagie/text/pdf/BaseField.java
  openpdf/src/main/java/com/lowagie/text/pdf/BidiLine.java
  openpdf/src/main/java/com/lowagie/text/pdf/CFFFont.java
  openpdf/src/main/java/com/lowagie/text/pdf/EnumerateTTC.java
  openpdf/src/main/java/com/lowagie/text/pdf/FdfWriter.java
Labels: Needs work, cleanup, help wanted, pr-needs-review

#223 Remove warnings 6
  openpdf/src/main/java/com/lowagie/text/pdf/CFFFontSubset.java
  openpdf/src/main/java/com/lowagie/text/pdf/FontDetails.java
  openpdf/src/main/java/com/lowagie/text/pdf/FontSelector.java
  openpdf/src/main/java/com/lowagie/text/pdf/MultiColumnText.java
  openpdf/src/main/java/com/lowagie/text/pdf/PageResources.java
  openpdf/src/main/java/com/lowagie/text/pdf/PdfAcroForm.java
  openpdf/src/main/java/com/lowagie/text/pdf/PdfArray.java
  openpdf/src/main/java/com/lowagie/text/pdf/PdfCopy.java
  openpdf/src/main/java/com/lowagie/text/pdf/PdfCopyFields.java
  openpdf/src/main/java/com/lowagie/text/pdf/PdfCopyFieldsImp.java
  openpdf/src/main/java/com/lowagie/text/pdf/PdfCopyForms.java
  openpdf/src/main/java/com/lowagie/text/pdf/draw/VerticalPositionMark.java
Labels: Needs work, cleanup, help wanted, need-info, pr-needs-review

#250 add close call to nested document
  openpdf/src/main/java/com/lowagie/text/pdf/PdfWriter.java
Labels: enhancement, help wanted, pr-needs-review
