Repository LibrePDF/OpenPDF, pull requests merged in 2023-01, with the labels that each got.

#815 Add CIDSet for font subset to ensure PDF/A compliance
  openpdf/src/main/java/com/lowagie/text/pdf/TrueTypeFontUnicode.java
  openpdf/src/test/java/com/lowagie/text/pdf/FontSubsetTest.java
  openpdf/src/test/java/com/lowagie/text/pdf/SubsetPrefixCreationTest.java
  openpdf/src/test/resources/fonts/liberation-serif/LiberationSerif-Regular.ttf
Labels: enhancement

#836 Throw InvalidPdfException in PdfReader.rebuildXref if no trailer is found
  openpdf/src/main/java/com/lowagie/text/pdf/PdfReader.java
Labels: bugfix

#841 Update javadoc on document class
  openpdf/src/main/java/com/lowagie/text/Document.java
Labels: documentation
